<Project>
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
    <NoWarn>$(NoWarn);CA1014;CA2007;CS8002;NU1900;NU1901;NU1902;NU1903;NU1904</NoWarn>
  </PropertyGroup>
</Project>
