import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const source = JSON.parse(await readFile(join(root, 'tokens/tokens.json'), 'utf8'));
const css = `/* Generated from ui/tokens/tokens.json. Do not edit. */\n:root {\n  --color-slate-50: ${source.color.slate['50'].$value};\n  --color-slate-100: ${source.color.slate['100'].$value};\n  --color-slate-300: ${source.color.slate['300'].$value};\n  --color-slate-500: ${source.color.slate['500'].$value};\n  --color-slate-700: ${source.color.slate['700'].$value};\n  --color-slate-900: ${source.color.slate['900'].$value};\n  --color-blue-600: ${source.color.blue['600'].$value};\n  --color-blue-700: ${source.color.blue['700'].$value};\n  --color-red-700: ${source.color.red['700'].$value};\n  --color-green-700: ${source.color.green['700'].$value};\n  --color-amber-700: ${source.color.amber['700'].$value};\n  --color-white: ${source.color.white.$value};\n  --space-1: ${source.space['1'].$value}; --space-2: ${source.space['2'].$value}; --space-3: ${source.space['3'].$value}; --space-4: ${source.space['4'].$value}; --space-6: ${source.space['6'].$value}; --space-8: ${source.space['8'].$value};\n  --radius-sm: ${source.radius.sm.$value}; --radius-md: ${source.radius.md.$value}; --radius-lg: ${source.radius.lg.$value}; --radius-full: ${source.radius.full.$value};\n  --font-sans: ${source.font.sans.$value}; --font-body: ${source.font.body.$value}; --font-small: ${source.font.small.$value}; --font-large: ${source.font.large.$value}; --font-title: ${source.font.title.$value};\n  --color-background: var(--color-slate-50); --color-surface: var(--color-white); --color-foreground: var(--color-slate-900); --color-muted: var(--color-slate-100); --color-muted-foreground: var(--color-slate-700); --color-primary: var(--color-blue-600); --color-primary-hover: var(--color-blue-700); --color-danger: var(--color-red-700); --color-success: var(--color-green-700); --color-warning: var(--color-amber-700); --focus-ring: var(--color-blue-600);\n}\n[data-theme="dark"], .theme-dark { --color-background: var(--color-slate-900); --color-surface: var(--color-slate-700); --color-foreground: var(--color-slate-50); --color-muted: var(--color-slate-700); --color-muted-foreground: var(--color-slate-100); --color-primary: #93c5fd; --color-primary-hover: #bfdbfe; --color-danger: #fca5a5; --color-success: #86efac; --color-warning: #fcd34d; --focus-ring: #bfdbfe; }\n@media (prefers-reduced-motion: reduce) { *, *::before, *::after { animation-duration: 0.01ms !important; animation-iteration-count: 1 !important; scroll-behavior: auto !important; transition-duration: 0.01ms !important; } }\n`;
const ts = `/** Generated from tokens.json. */\nexport const tokens = { color: { background: 'var(--color-background)', surface: 'var(--color-surface)', foreground: 'var(--color-foreground)', primary: 'var(--color-primary)', danger: 'var(--color-danger)', success: 'var(--color-success)', warning: 'var(--color-warning)' }, space: { 1: 'var(--space-1)', 2: 'var(--space-2)', 3: 'var(--space-3)', 4: 'var(--space-4)', 6: 'var(--space-6)', 8: 'var(--space-8)' } } as const;\nexport type PlatformTheme = 'light' | 'dark';\n`;
const output = join(root, 'packages/design-tokens/dist');
await mkdir(output, { recursive: true });
await writeFile(join(output, 'tokens.css'), css);
await writeFile(join(output, 'tokens.ts'), ts);
