<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Platform.Starter\Platform.Starter.csproj" />
  </ItemGroup>
</Project>
