<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Platform.Core" Version="0.1.*" />
    <PackageReference Include="Platform.Core.Testing" Version="0.1.0" />
  </ItemGroup>

</Project>
