<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
    <ProjectReference Include="../../src/Platform.Identity.Contracts/Platform.Identity.Contracts.csproj" />
    <ProjectReference Include="../../src/Platform.Authorization/Platform.Authorization.csproj" />
    <ProjectReference Include="../../src/Platform.Identity.AspNetCore/Platform.Identity.AspNetCore.csproj" />
    <ProjectReference Include="../../src/Platform.Identity.Testing/Platform.Identity.Testing.csproj" />
  </ItemGroup>
</Project>
